---
title: "AMP ID Search"
format: html
editor: source
---

## Load Packages

```{r}
#| output: false
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, RPostgres, DBI, here, stringr)

```

## Connect to `survey_data` schema in `ribbitr` database
```{r}
#| output: false
tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv,
                 dbname = Sys.getenv("aws_dbname"),
                 host = Sys.getenv("aws_host"),
                 port = Sys.getenv("aws_port"),
                 user = Sys.getenv("aws_user"),
                 password = Sys.getenv("aws_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

#search path
dbExecute(connection, "set search_path to survey_data")

```

## Query DB for `bd_swab_id`, `amp_id`, and `average_copy_number`
```{r}

q <- "select r.region, s.site, v.date, s2.detection_type, c.species_capture, c.svl_mm, c.body_mass_g, c.sex, c.life_stage,
      c.bd_swab_id, c.amp_id, bd.average_copy_number
      from region r
      join site s on r.region_id = s.region_id
      join visit v on s.site_id = v.site_id
      join survey s2 on v.visit_id = s2.visit_id
      join capture c on s2.survey_id = c.survey_id
      join penn_22_bd_results bd on c.bd_swab_id = bd.bd_swab_id;"


bd_results <- dbGetQuery(connection, q) %>% 
  mutate(across(where(is.character), str_to_lower))


```


## Read in AMP IDs
```{r}

amp_ids <- read_csv(here("data", "PLE_GIA.csv")) %>% 
  mutate(across(where(is.character), str_to_lower)) %>% 
  select(!c(missing))

```

## Join Bd results onto Amp ID
```{r}

final_table <- amp_ids %>% 
  left_join(bd_results, by = c("amp_id")) %>% 
  mutate(amp_id = if_else(amp_id == "ampbath00037", "ampbath00037-NegC", amp_id),
         amp_id = if_else(amp_id == "ampbath00049", "ampbath00049-NegC", amp_id),
         amp_id = if_else(amp_id == "ampbath00005", "ampbath00005-Dub", amp_id),
         amp_id = if_else(amp_id == "ampbath00017", "ampbath00017-Dub", amp_id),
         amp_id = if_else(amp_id == "ampbath00019", "ampbath00019-Dub", amp_id),
         amp_id = if_else(amp_id == "ampbath00021", "ampbath00021-Dub", amp_id)) %>% 
  write_csv(here("GIA_BdResults.csv"))

```

